language: python
python:
  - "2.6"
  - "2.7"
env:
  - TORNADO_VERSION=2.4.1
  - TORNADO_VERSION=3.0.2
  - TORNADO_VERSION=3.1.1
  - TORNADO_VERSION=3.2
install:
  - "pip install simplejson"
  - "export PYCURL_SSL_LIBRARY=openssl"
  - "pip install pycurl"
  - "pip install tornado==$TORNADO_VERSION"
script: py.test
notifications:
  email: false
